name: restmex
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - catalogue=2.0.10
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpathlib=0.21.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - confection=0.1.5
  - cymem=2.0.11
  - cython-blis=1.0.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - jinja2=3.1.6
  - joblib=1.4.2
  - langcodes=3.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=20.1.3
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - llvm-openmp=20.1.3
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - murmurhash=1.0.10
  - narwhals=1.37.0
  - ncurses=6.5
  - numpy=2.2.5
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - pip=25.1
  - plotly=6.0.1
  - preshed=3.0.9
  - pycparser=2.22
  - pydantic=2.11.3
  - pydantic-core=2.33.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - readline=8.2
  - requests=2.32.3
  - rich=14.0.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=79.0.1
  - shellingham=1.5.4
  - six=1.17.0
  - smart-open=7.1.0
  - smart_open=7.1.0
  - spacy=3.8.5
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.5.1
  - thinc=8.3.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typer=0.15.3
  - typer-slim=0.15.3
  - typer-slim-standard=0.15.3
  - typing-extensions=4.13.2
  - typing-inspection=0.4.0
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ujson=5.10.0
  - urllib3=2.4.0
  - wasabi=1.1.3
  - weasel=0.4.1
  - wheel=0.45.1
  - wrapt=1.17.2
  - zstandard=0.23.0
  - radicli=0.0.25
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.57.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - pillow==11.2.1
      - pyparsing==3.2.3
      - wordcloud==1.9.4